import { QuestionPaper as IQP } from '../../types';
import { SectionBlock } from './SectionBlock';
import { formatDate } from '../../lib/utils';

interface Props { paper: IQP }

export function QuestionPaper({ paper }: Props) {
  let qNum = 1;
  const totalQ = paper.sections.reduce((s, sec) => s + sec.questions.length, 0);

  // Collect all questions with answers for the Answer Key
  const allQA = paper.sections.flatMap((sec) =>
    sec.questions.filter((q) => q.answer || q.options)
  );

  return (
    <div className="mx-auto max-w-3xl bg-white shadow-sm print:shadow-none print:max-w-none">

      {/* ── School / Institution Header ── */}
      <div className="border-b-2 border-gray-800 px-10 py-8 text-center">
        <h1 className="text-xl font-extrabold uppercase tracking-wide text-gray-900">
          {paper.title}
        </h1>
        <div className="mt-3 flex flex-wrap items-center justify-center gap-6 text-sm text-gray-700">
          <span><strong>Subject:</strong> {paper.subject}</span>
          {paper.dueDate && <span><strong>Date:</strong> {formatDate(paper.dueDate)}</span>}
          <span><strong>Maximum Marks:</strong> {paper.totalMarks}</span>
        </div>
      </div>

      <div className="px-10 py-6">

        {/* ── Student Info ── */}
        <div className="mb-4 grid grid-cols-3 gap-6 border-b border-gray-200 pb-4">
          {['Name', 'Roll Number', 'Class / Section'].map((lbl) => (
            <div key={lbl}>
              <p className="text-xs font-semibold text-gray-500">{lbl}:</p>
              <div className="mt-2 h-px w-full bg-gray-400" />
            </div>
          ))}
        </div>

        {/* ── Instructions ── */}
        <div className="mb-6 rounded-lg border border-gray-100 bg-gray-50 px-5 py-3 text-xs text-gray-600">
          <strong>Instructions:</strong> All questions are compulsory unless stated otherwise.
          Marks for each question are indicated in brackets.
        </div>

        {/* ── Sections ── */}
        <div className="space-y-8">
          {paper.sections.map((sec) => {
            const start = qNum;
            qNum += sec.questions.length;
            return <SectionBlock key={sec.sectionLabel} section={sec} startNumber={start} />;
          })}
        </div>

        {/* ── End of Question Paper ── */}
        <div className="my-6 text-center text-sm font-semibold text-gray-500 italic">
          — End of Question Paper —
        </div>

        {/* ── Answer Key ── */}
        {allQA.length > 0 && (
          <div className="mt-4 border-t-2 border-dashed border-gray-300 pt-6">
            <h2 className="mb-4 text-base font-bold text-gray-900">Answer Key:</h2>
            <div className="space-y-3">
              {paper.sections.flatMap((sec, si) =>
                sec.questions
                  .filter((q) => q.answer || (q.type === 'MCQ' && q.options))
                  .map((q, qi) => {
                    const globalNum = paper.sections
                      .slice(0, si)
                      .reduce((s, s2) => s + s2.questions.length, 0) + qi + 1;

                    // For MCQ, find the correct option letter
                    let ans = q.answer ?? '';
                    if (!ans && q.type === 'MCQ' && q.options) {
                      ans = `(A) ${q.options[0]}`; // fallback
                    }

                    return (
                      <div key={`${si}-${qi}`} className="text-sm">
                        <span className="font-semibold text-gray-800">{globalNum}.</span>{' '}
                        <span className="text-gray-700">{ans}</span>
                      </div>
                    );
                  })
              )}
            </div>
          </div>
        )}

        {/* ── Footer ── */}
        <div className="mt-8 border-t border-gray-100 pt-4 text-center text-[10px] text-gray-300">
          Generated by VedaAI · {paper.metadata.llmModel} · {formatDate(paper.metadata.generatedAt)}
        </div>
      </div>
    </div>
  );
}
