import { QuestionPaper as IQP } from '../../types';
import { SectionBlock } from './SectionBlock';
import { formatDate } from '../../lib/utils';

interface Props { 
  paper: IQP;
  profileName?: string;
}

export function QuestionPaper({ paper, profileName }: Props) {
  let qNum = 1;
  const totalQ = paper.sections.reduce((s, sec) => s + sec.questions.length, 0);

  // Collect all questions with answers for the Answer Key
  const allQA = paper.sections.flatMap((sec) =>
    sec.questions.filter((q) => q.answer || q.options)
  );

  return (
    <div className="mx-auto max-w-3xl bg-white rounded-[32px] shadow-sm print:shadow-none print:max-w-none">

      {/* ── School / Institution Header ── */}
      <div className="px-10 pt-12 pb-6 text-center">
        <h1 className="text-2xl font-bold tracking-tight text-gray-900 mb-2">
          {profileName || 'Delhi Public School'}
        </h1>
        <h2 className="text-lg font-semibold text-gray-800 mb-1">
          Subject: {paper.subject}
        </h2>
        <h3 className="text-lg font-semibold text-gray-800 mb-8">
          Class: {paper.className || '5th'}
        </h3>
        
        <div className="flex justify-between items-center text-sm font-semibold text-gray-800 mb-6">
          <span>Time Allowed: 45 minutes</span>
          <span>Maximum Marks: {paper.totalMarks}</span>
        </div>

        <div className="text-left text-sm font-semibold text-gray-800 mb-6">
          All questions are compulsory unless stated otherwise.
        </div>

        {/* ── Student Info ── */}
        <div className="text-left space-y-2 text-sm font-semibold text-gray-800 border-b-2 border-transparent pb-4">
          <div>Name: ____________________</div>
          <div>Roll Number: ____________________</div>
          <div>Class: {paper.className || '5th'} Section: ____________________</div>
        </div>
      </div>

      <div className="px-10 pb-10">

        {/* ── Sections ── */}
        <div className="space-y-8">
          {paper.sections.map((sec) => {
            const start = qNum;
            qNum += sec.questions.length;
            return <SectionBlock key={sec.sectionLabel} section={sec} startNumber={start} />;
          })}
        </div>

        {/* ── End of Question Paper ── */}
        <div className="my-8 text-sm font-bold text-gray-900">
          End of Question Paper
        </div>

        {/* ── Answer Key ── */}
        {allQA.length > 0 && (
          <div className="mt-8 pt-6">
            <h2 className="mb-4 text-base font-bold text-gray-900">Answer Key:</h2>
            <div className="space-y-3">
              {paper.sections.flatMap((sec, si) =>
                sec.questions
                  .filter((q) => q.answer || (q.type === 'MCQ' && q.options))
                  .map((q, qi) => {
                    const globalNum = paper.sections
                      .slice(0, si)
                      .reduce((s, s2) => s + s2.questions.length, 0) + qi + 1;

                    // For MCQ, find the correct option letter
                    let ans = q.answer ?? '';
                    if (!ans && q.type === 'MCQ' && q.options) {
                      ans = `(A) ${q.options[0]}`; // fallback
                    }

                    return (
                      <div key={`${si}-${qi}`} className="text-sm">
                        <span className="font-semibold text-gray-800">{globalNum}.</span>{' '}
                        <span className="text-gray-700">{ans}</span>
                      </div>
                    );
                  })
              )}
            </div>
          </div>
        )}

        {/* ── Footer ── */}
        <div className="mt-8 border-t border-gray-100 pt-4 text-center text-[10px] text-gray-300">
          Generated by VedaAI · {paper.metadata.llmModel} · {formatDate(paper.metadata.generatedAt)}
        </div>
      </div>
    </div>
  );
}
